luggageshare/apps/luggage/urls.py
# coding: utf-8
from django.conf.urls import url
from django.views.generic import RedirectView

from luggageshare.apps.luggage import views

urlpatterns = [
    url(r'^luggage/(?P<pk>[0-9]+)/update/$', views.LuggageUpdateView.as_view(), name='luggage_update'),
    url(r'^luggage/(?P<pk>[0-9]+)/delete/$', views.LuggageDeleteView.as_view(), name='luggage_delete'),
    url(r'^luggage/(?P<pk>[0-9]+)/$', views.LuggageDetailView.as_view(), name='luggage_detail'),
    url(r'^luggage/create/$', views.LuggageCreateView.as_view(), name='luggage_create'),
    url(r'^luggage/my/$', views.UserLuggageListView.as_view(), name='luggage_user_list'),
    url(r'^luggage/$', views.LuggageListView.as_view(), name='luggage_list'),
    url(r'^$', RedirectView.as_view(url='/luggage/'), name='home'),
]

luggageshare/apps/profile/urls.py
# coding: utf-8

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from luggageshare.apps.profile import views

urlpatterns = [
    url(
        r'^login/$',
        auth_views.login,
        {
            'template_name': 'profile/login.html'
        },
        name='login'
    ),
    url(
        r'^logout/$',
        auth_views.logout,
        {
            'next_page': '/'
        },
        name='logout'
    ),
    url(
        r'^password_change/$',
        auth_views.password_change,
        {
            'template_name': 'profile/password_change.html',
            'post_change_redirect': 'profile:password_change_done'
        },
        name='password_change'
    ),
    url(
        r'^password_change/done/$',
        auth_views.password_change_done,
        {
            'template_name': 'profile/password_change_done.html'
        },
        name='password_change_done'
    ),
    url(
        r'^password_reset/$',
        auth_views.password_reset,
        {
            'template_name': 'profile/password_reset.html',
            'post_reset_redirect': 'profile:password_reset_done',
            'email_template_name': 'profile/password_reset_email.html',
            'from_email': 'info@luggageshare.com'
        },
        name='password_reset'
    ),
    url(
        r'^password_reset/done/$',
        auth_views.password_reset_done,
        {
            'template_name': 'profile/password_reset_done.html'
        },
        name='password_reset_done'
    ),
    url(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {
            'template_name': 'profile/password_reset_confirm.html',
            'post_reset_redirect': 'profile:password_reset_complete'
        },
        name='password_reset_confirm'
    ),
    url(
        r'^reset/done/$',
        auth_views.password_reset_complete,
        {
            'template_name': 'profile/password_reset_complete.html',
        },
        name='password_reset_complete'
    ),
    url(
        r'^register/$',
        views.RegisterView.as_view(),
        name='register'
    ),
    url(
        r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.register_confirm,
        name='register_confirm'
    ),
    url(
        r'^confirm/done/$',
        views.RegisterConfirmDone.as_view(),
        name='register_confirm_done'
    ),
    url(
        r'^update/$',
        views.ProfileUpdate.as_view(),
        name='update'
    ),
    url(
        r'^preferences/$',
        views.ProfilePreferences.as_view(),
        name='preferences'
    ),
    url(
        r'$',
        views.ProfileView.as_view(),
        name='profile'
    )
]

luggageshare/urls.py
# coding: utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^', include('luggageshare.apps.luggage.urls', namespace='luggage')),
    url('^profile/', include('luggageshare.apps.profile.urls', namespace='profile')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'LuggageShare admin'

luggageshare/apps/message/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

luggageshare/apps/luggage/forms.py
# coding: utf-8
from django import forms

from luggageshare.apps.luggage.models import Luggage


class LuggageForm(forms.ModelForm):
    class Meta:
        model = Luggage
        fields = (
            'departure',
            'departure_date',
            'arrival',
            'arrival_date',
            'size',
            'weight',
            'weight_mu',
            'price',
            'currency',
            'note'
        )

luggageshare/apps/profile/forms.py
# coding: utf-8

from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.core.exceptions import MultipleObjectsReturned
from django.utils.translation import ugettext as _

from luggageshare.apps.currency.models import Currency


class RegisterForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
        'existent_email': _("A user with that username already exists.")
    }
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as before, for verification."))

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            User.objects.get(email=email)
            raise forms.ValidationError(
                self.error_messages['existent_email'],
                code='existent_email',
            )
        except MultipleObjectsReturned:
            raise forms.ValidationError(
                self.error_messages['existent_email'],
                code='existent_email',
            )
        except User.DoesNotExist:
            return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

luggageshare/apps/currency/views.py
from django.shortcuts import render

# Create your views here.

luggageshare/apps/luggage/views.py
# coding: utf-8
import datetime
from decimal import Decimal

from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.shortcuts import redirect
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView
from django.views.generic.edit import FormMixin

from luggageshare.apps.luggage.forms import LuggageForm
from luggageshare.apps.luggage.models import Luggage


class ComingSoon(TemplateView):
    template_name = 'coming_soon.html'


class LuggageCreateView(CreateView):
    model = Luggage
    form_class = LuggageForm
    template_name = 'luggage/luggage_create.html'
    success_url = reverse_lazy('luggage:luggage_list')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return super(LuggageCreateView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect('luggage:luggage_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.status = 'published'
        return super(LuggageCreateView, self).form_valid(form)


class LuggageUpdateView(UpdateView):
    form_class = LuggageForm
    template_name = 'luggage/luggage_create.html'
    success_url = reverse_lazy('profile:profile')

    def get_queryset(self):
        return Luggage.objects.filter(user=self.request.user).exclude(status__in=['done', 'removed', 'accepted'])

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(LuggageUpdateView, self).form_valid(form)


class LuggageDetailView(DetailView):
    model = Luggage
    template_name = 'luggage/luggage_detail.html'


class LuggageDeleteView(DetailView):
    template_name = 'luggage/luggage_delete.html'

    def get_queryset(self):
        return Luggage.objects.filter(user=self.request.user)

    def post(self, request, *args, **kwargs):
        luggage = self.get_object()
        luggage.delete_luggage()
        return redirect('luggage:luggage_list')


class LuggageListView(FormMixin, ListView):
    model = Luggage
    form_class = LuggageForm
    template_name = 'luggage/luggage_list.html'
    paginate_by = 10
    title = 'Luggage list'

    def __init__(self, **kwargs):
        self.filter_dict = None
        self.kg_filter = Q(weight__gte=0, weight_mu__iexact=u'kg')
        self.lbs_filter = Q(weight__gte=0, weight_mu__iexact=u'lbs')
        super(LuggageListView, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        self.filter_dict = dict()
        self.initial = dict()
        for key in request.GET:
            value = request.GET.get(key, None)
            if value:
                if key in ['departure_date', 'arrival_date']:
                    value = datetime.datetime.strptime(value, '%d/%m/%Y %H:%M')
                    self.filter_dict[key] = value
                elif key in ['weight']:
                    if hasattr(request.user, 'profile'):
                        weight_mu = request.user.profile.weight_mu
                    else:
                        weight_mu = u'kg'
                    if weight_mu == u'kg':
                        converted = round(Decimal(value) * Decimal(0.4535923), 2)
                        self.kg_filter = Q(weight__gte=value, weight_mu__iexact=u'kg')
                        self.lbs_filter = Q(weight__gte=converted, weight_mu__iexact=u'lbs')
                    elif weight_mu == u'lbs':
                        converted = round(Decimal(value) * Decimal(2.204622), 2)
                        self.lbs_filter = Q(weight__gte=value, weight_mu__iexact=u'lbs')
                        self.kg_filter = Q(weight__gte=converted, weight_mu__iexact=u'kg')
                else:
                    self.filter_dict['{}__icontains'.format(key)] = value
                self.initial[key] = value
        return super(LuggageListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(LuggageListView, self).get_context_data(**kwargs)
        ctx['title'] = self.title
        return ctx

    def get_queryset(self):
        qs = self.model.objects.filter(
            status='published',
            departure_date__gt=datetime.datetime.now(),
            **self.filter_dict
        )
        return qs.filter(self.kg_filter | self.lbs_filter).order_by('-created')


class UserLuggageListView(LuggageListView):
    title = 'My luggage'

    def get_queryset(self):
        return self.model.objects.filter(
            user=self.request.user
        ).exclude(
            status__in=['done', 'removed', 'accepted']
        )

luggageshare/apps/message/views.py
from django.shortcuts import render

# Create your views here.

luggageshare/apps/profile/views.py
# coding: utf-8

from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.template import loader
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.decorators import cache, debug
from django.views.generic import TemplateView, FormView, UpdateView

from luggageshare.apps.profile.forms import RegisterForm
from luggageshare.apps.profile.models import Profile


class ProfileView(TemplateView):
    template_name = 'profile/profile.html'

    def __init__(self, **kwargs):
        self.profile = None
        super(ProfileView, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, 'profile'):
            self.profile = request.user.profile
        else:
            return redirect('profile:login')
        return super(ProfileView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(ProfileView, self).get_context_data(**kwargs)
        ctx['profile'] = self.profile
        return ctx


class RegisterView(FormView):
    form_class = RegisterForm
    success_url = '/'
    template_name = 'profile/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('profile:profile')
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save()
        self.send_confirmation_email(user)
        messages.add_message(
            self.request, messages.INFO,
            u"""
                Thanks for registering. An email has been sent to your address.
                Please click on the link in the email to confirm your address
            """
        )
        return super(RegisterView, self).form_valid(form)

    def send_confirmation_email(self, user):
        current_site = get_current_site(self.request)
        site_name = current_site.name
        domain = current_site.domain

        context = {
            'email': user.email,
            'domain': domain,
            'site_name': site_name,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'user': user,
            'token': default_token_generator.make_token(user),
            'protocol': 'https' if self.request.is_secure() else 'http',
        }
        subject = loader.render_to_string('profile/register_confirm_subject.txt', context)
        subject = ''.join(subject.splitlines())
        body = loader.render_to_string('profile/register_confirm_email.html', context)
        email_message = EmailMultiAlternatives(subject, body, 'info@luggageshare.com', [user.email])
        html_email = loader.render_to_string('profile/register_confirm_email.html', context)
        email_message.attach_alternative(html_email, 'text/html')

        email_message.send()


@debug.sensitive_post_parameters()
@cache.never_cache
def register_confirm(request, uidb64=None, token=None):
    assert uidb64 is not None and token is not None  # checked by URLconf

    try:
        # urlsafe_base64_decode() decodes to bytestring on Python 3
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()

        return redirect('profile:register_confirm_done')

    return redirect('profile:login')


class RegisterConfirmDone(TemplateView):
    template_name = 'profile/register_confirm_done.html'


class ProfileUpdate(UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email']
    template_name = 'profile/update.html'
    success_url = reverse_lazy('profile:profile')

    def __init__(self, **kwargs):
        self.user = None
        super(ProfileUpdate, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            self.user = request.user
        else:
            redirect('profile:login')
        return super(ProfileUpdate, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return self.user


class ProfilePreferences(UpdateView):
    model = Profile
    fields = ['weight_mu', 'currency']
    template_name = 'profile/preferences.html'
    success_url = reverse_lazy('profile:profile')

    def __init__(self, **kwargs):
        self.profile = None
        super(ProfilePreferences, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated() and hasattr(request.user, 'profile'):
            self.profile = request.user.profile
        else:
            redirect('profile:login')
        return super(ProfilePreferences, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return self.profile

luggageshare/templates/profile/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="text-center">Login</h2>
            <form method="post" action="">
                {% csrf_token %}
                {% for field in form %}
                  {% include '_form_field.html' %}
                {% endfor %}
                <input type="submit" value="Login" class="btn btn-primary">
                <a class="pull-right" href="{% url 'profile:password_reset' %}">Forgotten your password?</a>
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
            <br>

        </div>
    </div>
{% endblock content %}

luggageshare/templates/profile/password_change.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="text-center">Change password</h2>
            <form method="post" action="{% url 'profile:password_change' %}">
                {% csrf_token %}
                {% for field in form %}
                    {% include '_form_field.html' %}
                {% endfor %}
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>

{% endblock content %}

luggageshare/templates/profile/password_change_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="text-center">Change password</h2>
        <p>{% trans 'Your password was changed.' %}</p>
    </div>
</div>
{% endblock %}

luggageshare/templates/profile/password_reset.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="text-center">Reset password</h2>
            <form method="post" action="{% url 'profile:password_reset' %}">
                {% csrf_token %}
                {% for field in form %}
                    {% include '_form_field.html' %}
                {% endfor %}
                <input type="submit" value="Reset password" class="btn btn-primary">
            </form>
        </div>
    </div>
{% endblock content %}

luggageshare/templates/profile/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="text-center">Confirm new password</h2>
        <p>
            {% trans "Your password has been set.  You may go ahead and log in now." %}
            <a href="{% url 'profile:login' %}">{% trans 'Click here to log in.' %}</a>
        </p>
    </div>
</div>
{% endblock %}

luggageshare/templates/profile/password_reset_confirm.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="text-center">Confirm new password</h2>
        {% if validlink %}
        <p>
          {% trans "Please enter your new password twice so we can verify you typed it in correctly." %}
        </p>

        <form method="post">
          {% csrf_token %}
          {% for field in form %}
            {% include '_form_field.html' %}
          {% endfor %}
        <input type="submit" value="{% trans 'Change my password' %}" class="btn btn-primary">
        </form>

        {% else %}

        <p>
          {% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}
        </p>

        {% endif %}
    </div>
</div>

{% endblock %}

luggageshare/templates/profile/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="text-center">Reset password</h2>
        <p>
            {% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}
        </p>

        <p>
            {% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}
        </p>
    </div>
</div>

{% endblock %}

luggageshare/templates/profile/password_reset_email.html
{% extends 'registration/password_reset_email.html' %}

{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'profile:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

luggageshare/templates/profile/preferences.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="text-center">Profile preferences</h2>
        <form method="post" action="">
            {% csrf_token %}
            {% for field in form %}
                {% include '_form_field.html' %}
            {% endfor %}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</div>
{% endblock content %}

luggageshare/templates/profile/profile.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        <div class="col-md-12 text-center">
            <h3>User profile</h3>
            <h2>{{ profile.user.username }}</h2>
            <h4>{{ profile.user.first_name }} {{ profile.user.last_name }}</h4>
            <h4>{{ profile.user.email }}</h4>
            {% if profile.avatar %}
                <img src="{{ profile.avatar.url }}" alt="{{ profile.user.username }}">
            {% endif %}
        </div>
    </div>

{% endblock content %}

luggageshare/templates/profile/register.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="text-center">Register</h2>
        <form method="post" action="{% url 'profile:register' %}">
            {% csrf_token %}
            {% for field in form %}
                {% include '_form_field.html' %}
            {% endfor %}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</div>
{% endblock content %}

luggageshare/templates/profile/register_confirm_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="text-center">Email confirmed</h2>
        <p>
            {% trans "Your email has been confirmed. You may go ahead and log in now." %}
            <a href="{% url 'profile:login' %}">{% trans 'Click here to log in.' %}</a>
        </p>
    </div>
</div>

{% endblock %}

luggageshare/templates/profile/register_confirm_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you registered an user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and confirm your email:" %}
{{ protocol }}://{{ domain }}{% url 'profile:register_confirm' uidb64=uid token=token %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

luggageshare/templates/profile/update.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="text-center">Update profile</h2>
        <form method="post" action="">
            {% csrf_token %}
            {% for field in form %}
                {% include '_form_field.html' %}
            {% endfor %}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    </div>
</div>
{% endblock content %}