luggageshare/apps/luggage/urls.py
# coding: utf-8
from django.conf.urls import url
from django.views.generic import RedirectView

from luggageshare.apps.luggage import views

urlpatterns = [
    url(r'^luggage/(?P<pk>[0-9]+)/update/$', views.LuggageUpdateView.as_view(), name='luggage_update'),
    url(r'^luggage/(?P<pk>[0-9]+)/delete/$', views.LuggageDeleteView.as_view(), name='luggage_delete'),
    url(r'^luggage/(?P<pk>[0-9]+)/$', views.LuggageDetailView.as_view(), name='luggage_detail'),
    url(r'^luggage/create/$', views.LuggageCreateView.as_view(), name='luggage_create'),
    url(r'^luggage/my/$', views.UserLuggageListView.as_view(), name='luggage_user_list'),
    url(r'^luggage/$', views.LuggageListView.as_view(), name='luggage_list'),
    url(r'^$', RedirectView.as_view(url='/luggage/'), name='home'),
]

luggageshare/apps/profile/urls.py
# coding: utf-8

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from luggageshare.apps.profile import views

urlpatterns = [
    url(
        r'^login/$',
        auth_views.login,
        {
            'template_name': 'profile/login.html'
        },
        name='login'
    ),
    url(
        r'^logout/$',
        auth_views.logout,
        {
            'next_page': '/'
        },
        name='logout'
    ),
    url(
        r'^password_change/$',
        auth_views.password_change,
        {
            'template_name': 'profile/password_change.html',
            'post_change_redirect': 'profile:password_change_done'
        },
        name='password_change'
    ),
    url(
        r'^password_change/done/$',
        auth_views.password_change_done,
        {
            'template_name': 'profile/password_change_done.html'
        },
        name='password_change_done'
    ),
    url(
        r'^password_reset/$',
        auth_views.password_reset,
        {
            'template_name': 'profile/password_reset.html',
            'post_reset_redirect': 'profile:password_reset_done',
            'email_template_name': 'profile/password_reset_email.html',
            'from_email': 'info@luggageshare.com'
        },
        name='password_reset'
    ),
    url(
        r'^password_reset/done/$',
        auth_views.password_reset_done,
        {
            'template_name': 'profile/password_reset_done.html'
        },
        name='password_reset_done'
    ),
    url(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {
            'template_name': 'profile/password_reset_confirm.html',
            'post_reset_redirect': 'profile:password_reset_complete'
        },
        name='password_reset_confirm'
    ),
    url(
        r'^reset/done/$',
        auth_views.password_reset_complete,
        {
            'template_name': 'profile/password_reset_complete.html',
        },
        name='password_reset_complete'
    ),
    url(
        r'^register/$',
        views.RegisterView.as_view(),
        name='register'
    ),
    url(
        r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.register_confirm,
        name='register_confirm'
    ),
    url(
        r'^confirm/done/$',
        views.RegisterConfirmDone.as_view(),
        name='register_confirm_done'
    ),
    url(
        r'^update/$',
        views.ProfileUpdate.as_view(),
        name='update'
    ),
    url(
        r'^preferences/$',
        views.ProfilePreferences.as_view(),
        name='preferences'
    ),
    url(
        r'$',
        views.ProfileView.as_view(),
        name='profile'
    )
]

luggageshare/urls.py
# coding: utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^', include('luggageshare.apps.luggage.urls', namespace='luggage')),
    url('^profile/', include('luggageshare.apps.profile.urls', namespace='profile')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'LuggageShare admin'

luggageshare/apps/message/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

luggageshare/apps/luggage/forms.py
# coding: utf-8
from django import forms

from luggageshare.apps.luggage.models import Luggage


class LuggageForm(forms.ModelForm):
    class Meta:
        model = Luggage
        fields = (
            'departure',
            'departure_date',
            'arrival',
            'arrival_date',
            'size',
            'weight',
            'weight_mu',
            'price',
            'currency',
            'note'
        )

luggageshare/apps/profile/forms.py
# coding: utf-8

from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.core.exceptions import MultipleObjectsReturned
from django.utils.translation import ugettext as _

from luggageshare.apps.currency.models import Currency


class RegisterForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
        'existent_email': _("A user with that username already exists.")
    }
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as before, for verification."))

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            User.objects.get(email=email)
            raise forms.ValidationError(
                self.error_messages['existent_email'],
                code='existent_email',
            )
        except MultipleObjectsReturned:
            raise forms.ValidationError(
                self.error_messages['existent_email'],
                code='existent_email',
            )
        except User.DoesNotExist:
            return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

luggageshare/apps/currency/views.py
from django.shortcuts import render

# Create your views here.

luggageshare/apps/luggage/views.py
# coding: utf-8
import datetime
from decimal import Decimal

from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.shortcuts import redirect
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView
from django.views.generic.edit import FormMixin

from luggageshare.apps.luggage.forms import LuggageForm
from luggageshare.apps.luggage.models import Luggage


class ComingSoon(TemplateView):
    template_name = 'coming_soon.html'


class LuggageCreateView(CreateView):
    model = Luggage
    form_class = LuggageForm
    template_name = 'luggage/luggage_create.html'
    success_url = reverse_lazy('luggage:luggage_list')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return super(LuggageCreateView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect('luggage:luggage_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.status = 'published'
        return super(LuggageCreateView, self).form_valid(form)


class LuggageUpdateView(UpdateView):
    form_class = LuggageForm
    template_name = 'luggage/luggage_create.html'
    success_url = reverse_lazy('profile:profile')

    def get_queryset(self):
        return Luggage.objects.filter(user=self.request.user).exclude(status__in=['done', 'removed', 'accepted'])

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(LuggageUpdateView, self).form_valid(form)


class LuggageDetailView(DetailView):
    model = Luggage
    template_name = 'luggage/luggage_detail.html'


class LuggageDeleteView(DetailView):
    template_name = 'luggage/luggage_delete.html'

    def get_queryset(self):
        return Luggage.objects.filter(user=self.request.user)

    def post(self, request, *args, **kwargs):
        luggage = self.get_object()
        luggage.delete_luggage()
        return redirect('luggage:luggage_list')


class LuggageListView(FormMixin, ListView):
    model = Luggage
    form_class = LuggageForm
    template_name = 'luggage/luggage_list.html'
    paginate_by = 10
    title = 'Luggage list'

    def __init__(self, **kwargs):
        self.filter_dict = None
        self.kg_filter = Q(weight__gte=0, weight_mu__iexact=u'kg')
        self.lbs_filter = Q(weight__gte=0, weight_mu__iexact=u'lbs')
        super(LuggageListView, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        self.filter_dict = dict()
        self.initial = dict()
        for key in request.GET:
            value = request.GET.get(key, None)
            if value:
                if key in ['departure_date', 'arrival_date']:
                    value = datetime.datetime.strptime(value, '%d/%m/%Y %H:%M')
                    self.filter_dict[key] = value
                elif key in ['weight']:
                    if hasattr(request.user, 'profile'):
                        weight_mu = request.user.profile.weight_mu
                    else:
                        weight_mu = u'kg'
                    if weight_mu == u'kg':
                        converted = round(Decimal(value) * Decimal(0.4535923), 2)
                        self.kg_filter = Q(weight__gte=value, weight_mu__iexact=u'kg')
                        self.lbs_filter = Q(weight__gte=converted, weight_mu__iexact=u'lbs')
                    elif weight_mu == u'lbs':
                        converted = round(Decimal(value) * Decimal(2.204622), 2)
                        self.lbs_filter = Q(weight__gte=value, weight_mu__iexact=u'lbs')
                        self.kg_filter = Q(weight__gte=converted, weight_mu__iexact=u'kg')
                else:
                    self.filter_dict['{}__icontains'.format(key)] = value
                self.initial[key] = value
        return super(LuggageListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(LuggageListView, self).get_context_data(**kwargs)
        ctx['title'] = self.title
        return ctx

    def get_queryset(self):
        qs = self.model.objects.filter(
            status='published',
            departure_date__gt=datetime.datetime.now(),
            **self.filter_dict
        )
        return qs.filter(self.kg_filter | self.lbs_filter).order_by('-created')


class UserLuggageListView(LuggageListView):
    title = 'My luggage'

    def get_queryset(self):
        return self.model.objects.filter(
            user=self.request.user
        ).exclude(
            status__in=['done', 'removed', 'accepted']
        )

luggageshare/apps/message/views.py
from django.shortcuts import render

# Create your views here.

luggageshare/apps/profile/views.py
# coding: utf-8

from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.template import loader
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.decorators import cache, debug
from django.views.generic import TemplateView, FormView, UpdateView

from luggageshare.apps.profile.forms import RegisterForm
from luggageshare.apps.profile.models import Profile


class ProfileView(TemplateView):
    template_name = 'profile/profile.html'

    def __init__(self, **kwargs):
        self.profile = None
        super(ProfileView, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, 'profile'):
            self.profile = request.user.profile
        else:
            return redirect('profile:login')
        return super(ProfileView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(ProfileView, self).get_context_data(**kwargs)
        ctx['profile'] = self.profile
        return ctx


class RegisterView(FormView):
    form_class = RegisterForm
    success_url = '/'
    template_name = 'profile/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('profile:profile')
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save()
        self.send_confirmation_email(user)
        messages.add_message(
            self.request, messages.INFO,
            u"""
                Thanks for registering. An email has been sent to your address.
                Please click on the link in the email to confirm your address
            """
        )
        return super(RegisterView, self).form_valid(form)

    def send_confirmation_email(self, user):
        current_site = get_current_site(self.request)
        site_name = current_site.name
        domain = current_site.domain

        context = {
            'email': user.email,
            'domain': domain,
            'site_name': site_name,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'user': user,
            'token': default_token_generator.make_token(user),
            'protocol': 'https' if self.request.is_secure() else 'http',
        }
        subject = loader.render_to_string('profile/register_confirm_subject.txt', context)
        subject = ''.join(subject.splitlines())
        body = loader.render_to_string('profile/register_confirm_email.html', context)
        email_message = EmailMultiAlternatives(subject, body, 'info@luggageshare.com', [user.email])
        html_email = loader.render_to_string('profile/register_confirm_email.html', context)
        email_message.attach_alternative(html_email, 'text/html')

        email_message.send()


@debug.sensitive_post_parameters()
@cache.never_cache
def register_confirm(request, uidb64=None, token=None):
    assert uidb64 is not None and token is not None  # checked by URLconf

    try:
        # urlsafe_base64_decode() decodes to bytestring on Python 3
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()

        return redirect('profile:register_confirm_done')

    return redirect('profile:login')


class RegisterConfirmDone(TemplateView):
    template_name = 'profile/register_confirm_done.html'


class ProfileUpdate(UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email']
    template_name = 'profile/update.html'
    success_url = reverse_lazy('profile:profile')

    def __init__(self, **kwargs):
        self.user = None
        super(ProfileUpdate, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            self.user = request.user
        else:
            redirect('profile:login')
        return super(ProfileUpdate, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return self.user


class ProfilePreferences(UpdateView):
    model = Profile
    fields = ['weight_mu', 'currency']
    template_name = 'profile/preferences.html'
    success_url = reverse_lazy('profile:profile')

    def __init__(self, **kwargs):
        self.profile = None
        super(ProfilePreferences, self).__init__(**kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated() and hasattr(request.user, 'profile'):
            self.profile = request.user.profile
        else:
            redirect('profile:login')
        return super(ProfilePreferences, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return self.profile

luggageshare/templates/_date_field.html
<div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">
    <label class="control-label" for="{{field.id_for_label }}">{{field.label}}</label>
    <div class='input-group date' id="{{field.id_for_label }}">
        <input type='text' class="form-control" name="{{field.name}}" value="{{ field.value|date:'d/m/Y H:i' }}">
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
    </div>
    {{ field.errors }}
</div>
<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function() {
    $('#{{field.id_for_label}}').datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
      sideBySide: true,
    });
    {% if field.value %}
        var dateNow = new Date("{{ field.value|date:'F d, Y H:i:s' }}");
        $('#{{field.id_for_label}}').data("DateTimePicker").date(dateNow);
    {% endif %}
  });
</script>

luggageshare/templates/_form_field.html
{% load addcss %}

<div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">
  <label class="control-label" for="{{field.id}}">{{field.label}}</label>
  {{ field|addcss:"form-control" }}
  {% if field.errors %}
    <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
    {{ field.errors }}
  {% endif %}
</div>

luggageshare/templates/_maps_autocomplete.html
<script>
    var autocompleteDeparture;
    var autocompleteArrival;
    function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocompleteDeparture = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('id_departure')),
            {types: ['(cities)']});
        autocompleteArrival = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('id_arrival')),
            {types: ['(cities)']});
    }
</script>

luggageshare/templates/_navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'luggage:luggage_list' %}">LuggageShare</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'luggage:luggage_list' %}">Luggage</a></li>
        {% if user.is_authenticated %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'profile:profile' %}">Profile</a></li>
              <li><a href="{% url 'profile:update' %}">Update profile</a></li>
              <li><a href="{% url 'profile:preferences' %}">Profile preferences</a></li>
              <li><a href="{% url 'profile:password_change' %}">Change password</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'luggage:luggage_user_list' %}">My luggage</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'profile:logout' %}">Logout</a></li>
            </ul>
          </li>
        {% else %}
          <li>
            <a href="{% url 'profile:login' %}">Login</a>
          </li>
          <li>
            <a href="{% url 'profile:register' %}">Register</a>
          </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

luggageshare/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta name="description" content="{% block description %}{% endblock %}" />
    <meta name="keywords" content="{% block keywords %}{% endblock %}" />
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block title %}Luggageshare{% endblock title %}</title>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="icon" type="image/gif" href="{% static 'img/favicon.gif' %}">

    {% block css %}
      <!-- bower:css -->
      <!-- endbower -->
      <!-- inject:css -->
      <!-- endinject -->
    {% endblock %}

  </head>

  <body>

    <header>
      {% block header %}
      {% include '_navbar.html' %}
      {% endblock header %}
    </header>

    {% if messages %}
      <div class="messages container">
        {% for message in messages %}
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
          </div>
        {% endfor %}
      </div>
    {% endif %}

    <main class="container">

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </main>

    <footer>

    </footer>

    {% block javascript %}
      <!-- bower:js -->
      <!-- endbower -->
      <!-- inject:js -->
      <!-- endinject -->
    {% endblock javascript %}
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBaXIOaaEZFH39NJfcLO61yb3uUMk5vII&libraries=places&callback=initAutocomplete&language=en" async defer></script>
  </body>
</html>

luggageshare/templates/coming_soon.html
{% extends 'base.html' %}

{% block header %}{% endblock header %}

{% block css %}
<link href='https://fonts.googleapis.com/css?family=Raleway:700' rel='stylesheet' type='text/css'>
<style media="screen">
  body {
    margin: 0;
    font-family: 'Raleway', sans-serif;
  }
  main {
    height: 100vh;
    width: 100vw;
    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;
    justify-content: center;
    align-content: stretch;
    align-items: center;
    overflow: hidden;
    background-attachment: scroll;
    background-image: url("../static/cover.jpg");
    background-position: center center;
    background-repeat: none;
    background-size: cover;
  }
  h1 {
    font-size: 50px;
    color: #B1303C;
  }
</style>
{% endblock css%}

{% block content %}
<h1>Luggage Share</h1>
<h2>Coming soon...</h2>
{% endblock content %}